### PR TITLE
update module deps

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by markversfeld** [comment]
please merge and push to puppetforge

**Comment by jhoblitt** [comment]
@bodgit ping?

**Comment by parryb** [comment]
There is no version 4 it is suggested to move to [puppet-augeasproviders_core](https://forge.puppet.com/modules/puppet/augeasproviders_core)

**Comment by jhoblitt** [comment]
The constraint on augeasproviders_core is `< 4.0.0`, which would not allow 4.x.x. This PR was opened before there was a release of augeasproviders_core under the `puppet` forge namespace.

**Pull request merged**
